### ISSUE TITLE
ImportError: /tmp/_MEIg8WrG2/libcrypto.so.3: version `OPENSSL_3.3.0' not found

### ISSUE THREAD

**Issue by shayaknyc** [Arbitrate3280/LutrisToSunshine#2]
Running on arch linux, downloaded release and after adding sunshine credentials, received this error:

```
> ./lutristosunshine
Error executing command: Traceback (most recent call last):
  File "/usr/bin/lutris", line 61, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lutris/gui/application.py", line 37, in <module>
    from lutris.api import get_runners, parse_installer_url
  File "/usr/lib/python3.12/site-packages/lutris/api.py", line 20, in <module>
    from lutris.util import cache_single, http, system
  File "/usr/lib/python3.12/site-packages/lutris/util/http.py", line 6, in <module>
    import ssl
  File "/usr/lib/python3.12/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: /tmp/_MEImEh0j8/libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/python3.12/lib-dynload/_ssl.cpython-312-x86_64-linux-gnu.so)

No games found in Lutris, Heroic, or Bottles.
```

Not entirely sure how to go about fixing this....

**Comment by Arbitrate3280** [comment]
Can you test this and see if it works?

https://github.com/Arbitrate3280/LutrisToSunshine/actions/runs/11818704339/artifacts/2182139912

**Comment by Arbitrate3280** [comment]
https://github.com/Arbitrate3280/LutrisToSunshine/actions/runs/11830255043/artifacts/2185641306

give this one a try

**Comment by Arbitrate3280** [comment]
If this is still an issue let me know

**Comment by shayaknyc** [comment]
Hey, sorry for the delay!

> this artifact will expire soon, but I've updated the release binary to the new one:
> https://github.com/Arbitrate3280/LutrisToSunshine/releases/download/2.0.1/lutristosunshine

Yep! This one seemed to work! Thank you!
